---
title: "Quality Control Microbial Metagenomes"
output:
  html_document:
    keep_md: true
---

Describe prep. Less issues as a result. 20 samples, not 15.

Not using a loop beacuse outputting names that match mapping files and code used in the analysis. These names are not congruent with the SRA file names.

```{r, engine='bash', results='hide'}
mkdir microbial_qc

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p2_A346_corn.fastq.gz microbial_qc/B1_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p2_A3244_corn.fastq.gz microbial_qc/B2_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p2_A222_40mdgs.fastq.gz microbial_qc/B3_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p2_A3257_27cds.fastq.gz microbial_qc/B4_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p2_A259_55cs.fastq.gz microbial_qc/B5_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p3_A346_40mdgs.fastq.gz microbial_qc/B6_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p3_A3244_40mdgs.fastq.gz microbial_qc/B7_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p3_A222_corn.fastq.gz microbial_qc/B8_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p3_A3257_55cs.fastq.gz microbial_qc/B9_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p3_A259_27cds.fastq.gz microbial_qc/B10_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85

java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p4_A346_55cs.fastq.gz microbial_qc/B11_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
  
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p4_A3244_55cs.fastq.gz microbial_qc/B12_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p4_A222_27cds.fastq.gz microbial_qc/B13_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p4_A3257_corn.fastq.gz microbial_qc/B14_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p4_A259_40mdgs.fastq.gz microbial_qc/B15_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p1_A346_27cds.fastq.gz microbial_qc/B16_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p1_A3244_27cds.fastq.gz microbial_qc/B17_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p1_A222_55cs.fastq.gz microbial_qc/B18_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p1_A3257_40mdgs.fastq.gz microbial_qc/B19_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
    
java -jar trimmomatic-0.33.jar SE -phred33 raw_microbial/microbial_p1_A259_corn.fastq.gz microbial_qc/B20_trimm.fastq ILLUMINACLIP:total_adapt_remove.cat.txt:2:20:10 MINLEN:85
```

Now remove all artificial duplicates.

```{r, engine='bash', results='hide'}
export OMP_NUM_THREADS=10

for f in microbial_qc/*.fastq
do
  filename=$(basename "$f")
  filename="${filename%_*}"
  cd-hit-454 -i $f -o microbial_qc/"$filename""_finalQC.fastq" -M 6100 -T 10
done
```

Get a FASTA version.

```{r, engine='bash', results='hide'}
for f in microbial_qc/*finalQC.fastq
do
  filename=$(basename "$f")
  filename="${filename%.*}"
  fastq-to-fasta.py $f -o microbial_qc/"$filename"".fna"
done
```

Read counts.

```{r, engine='bash'}
grep -c ">" microbial_qc/*.fna
```

